name: 'PR'

on:
  pull_request:

permissions:
  checks: write
  contents: write

jobs:

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  build:
    name: Build
    uses: ./.github/workflows/build.yml
